### ISSUE TITLE
TODO list

### ISSUE THREAD

**Issue by MamaMuchu** [MamaMuchu/todo-list#2]
- [ ]  Create a web app page for the app
- [ ]  Document the code
- [ ]  Describe the app in README.md
- [ ] Add some styles to make it prettier with CSS3
- [ ]  Write the skeleton of the app with HTML5
